// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/data_soruce/profile_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/featuers/main_profile/api/main_profile_api_client.dart'
    as _i3;
import 'package:flowery/featuers/main_profile/data/model/profile_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileResponseModel_0 extends _i1.SmartFake
    implements _i2.ProfileResponseModel {
  _FakeProfileResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MainProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainProfileApiClient extends _i1.Mock
    implements _i3.MainProfileApiClient {
  MockMainProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileResponseModel> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i4.Future<_i2.ProfileResponseModel>.value(
              _FakeProfileResponseModel_0(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i4.Future<_i2.ProfileResponseModel>);
}
