// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/featuers/my_order/presentation/view_model/my_order_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/config/base_response/base_response.dart' as _i5;
import 'package:flowery/featuers/my_order/domain/entity/orders_entity_sprated.dart'
    as _i6;
import 'package:flowery/featuers/my_order/domain/repo/my_order_repo_contract.dart'
    as _i2;
import 'package:flowery/featuers/my_order/domain/use_case/get_my_order_data.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMyOrderRepoContract_0 extends _i1.SmartFake
    implements _i2.MyOrderRepoContract {
  _FakeMyOrderRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMyOrderData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyOrderData extends _i1.Mock implements _i3.GetMyOrderData {
  MockGetMyOrderData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MyOrderRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeMyOrderRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.MyOrderRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.OrdersEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.OrdersEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.OrdersEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.OrdersEntity>>);
}
