// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/app_language_logout/data/repositories/logout_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/config/user_helper/user_helper.dart' as _i4;
import 'package:flowery/features/app_language_logout/data/data_sources/logout_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LogoutRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutRemoteDataSource extends _i1.Mock
    implements _i2.LogoutRemoteDataSource {
  MockLogoutRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UserHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserHelper extends _i1.Mock implements _i4.UserHelper {
  MockUserHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isLogin() =>
      (super.noSuchMethod(Invocation.method(#isLogin, []), returnValue: false)
          as bool);

  @override
  _i3.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
