// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/view_model/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/config/base_response/base_response.dart' as _i5;
import 'package:flowery/featuers/main_profile/domain/entity/profile_entity.dart'
    as _i6;
import 'package:flowery/featuers/main_profile/domain/profile_repo/profile_repo_contract.dart'
    as _i2;
import 'package:flowery/featuers/main_profile/domain/use_case/profile_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepoContract_0 extends _i1.SmartFake
    implements _i2.ProfileRepoContract {
  _FakeProfileRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i3.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepoContract get profileRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepoContract),
            returnValue: _FakeProfileRepoContract_0(
              this,
              Invocation.getter(#profileRepoContract),
            ),
          )
          as _i2.ProfileRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.ProfileEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.ProfileEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.ProfileEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.ProfileEntity>>);
}
