// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/featuers/home/presentation/view_model/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/config/base_response/base_response.dart' as _i5;
import 'package:flowery/featuers/home/domain/home_enitiy/home_entity.dart'
    as _i6;
import 'package:flowery/featuers/home/domain/home_use_case/get_home_data_use_case.dart'
    as _i3;
import 'package:flowery/featuers/home/domain/repo_contract/home_repo_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepoContract_0 extends _i1.SmartFake
    implements _i2.HomeRepoContract {
  _FakeHomeRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetHomeDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeDataUseCase extends _i1.Mock
    implements _i3.GetHomeDataUseCase {
  MockGetHomeDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeHomeRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.HomeRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.HomeEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.HomeEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.HomeEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.HomeEntity>>);
}
