// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/featuers/home/data/repo_impl/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/config/base_response/base_response.dart' as _i4;
import 'package:flowery/featuers/home/data/data_source/home_remote_data_source_contract.dart'
    as _i2;
import 'package:flowery/featuers/home/data/models/response_model/home_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSourceContract extends _i1.Mock
    implements _i2.HomeRemoteDataSourceContract {
  MockHomeRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.HomeResponseModel>> getHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeData, []),
            returnValue: _i3.Future<_i4.Result<_i5.HomeResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.HomeResponseModel>>(
                this,
                Invocation.method(#getHomeData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.HomeResponseModel>>);
}
