// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6HOBNuER6o2oRYToz9CD0Xpv--biklM',
    appId: '1:824630695342:web:8be0e07a6429a43931643f',
    messagingSenderId: '824630695342',
    projectId: 'flowery-app-fb297',
    authDomain: 'flowery-app-fb297.firebaseapp.com',
    storageBucket: 'flowery-app-fb297.firebasestorage.app',
    measurementId: 'G-NYC2EVWZX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYU7XWhJkYPJn-Xg9M5Q7EZN2DJVYKqM',
    appId: '1:824630695342:android:7ac36bd6a018035331643f',
    messagingSenderId: '824630695342',
    projectId: 'flowery-app-fb297',
    storageBucket: 'flowery-app-fb297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1YoFuetlXi42dGZFFgCvJsYh6CgfKBE',
    appId: '1:824630695342:ios:0f36807a508653a931643f',
    messagingSenderId: '824630695342',
    projectId: 'flowery-app-fb297',
    storageBucket: 'flowery-app-fb297.firebasestorage.app',
    iosBundleId: 'com.example.flowery',
  );
}
