// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/edit_profile/data/repo/edit_profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;

import 'package:flowery/config/base_response/base_response.dart' as _i4;
import 'package:flowery/features/edit_profile/data/data_sources/edit_profile_remote_data_sources_contract.dart'
    as _i2;
import 'package:flowery/features/edit_profile/data/models/requests/edit_user_model.dart'
    as _i7;
import 'package:flowery/features/edit_profile/data/models/responses/get_user_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EditProfileRemoteDataSourcesContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileRemoteDataSourcesContract extends _i1.Mock
    implements _i2.EditProfileRemoteDataSourcesContract {
  MockEditProfileRemoteDataSourcesContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.GetUserResponseModel>> getCurrentLoggedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLoggedUser, []),
            returnValue: _i3.Future<_i4.Result<_i5.GetUserResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.GetUserResponseModel>>(
                this,
                Invocation.method(#getCurrentLoggedUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.GetUserResponseModel>>);

  @override
  _i3.Future<_i4.Result<_i5.GetUserResponseModel>> editUserProfile(
    _i7.EditUserModel? editUser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editUserProfile, [editUser]),
            returnValue: _i3.Future<_i4.Result<_i5.GetUserResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.GetUserResponseModel>>(
                this,
                Invocation.method(#editUserProfile, [editUser]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.GetUserResponseModel>>);

  @override
  _i3.Future<_i4.Result<_i5.GetUserResponseModel>> uploadUserPhoto(
    _i8.File? photo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadUserPhoto, [photo]),
            returnValue: _i3.Future<_i4.Result<_i5.GetUserResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.GetUserResponseModel>>(
                this,
                Invocation.method(#uploadUserPhoto, [photo]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.GetUserResponseModel>>);
}
