// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/edit_profile/presentation/view_model/cubit/edit_profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i11;

import 'package:flowery/config/base_response/base_response.dart' as _i5;
import 'package:flowery/features/edit_profile/data/models/requests/edit_user_model.dart'
    as _i9;
import 'package:flowery/features/edit_profile/domain/entities/user_entity.dart'
    as _i6;
import 'package:flowery/features/edit_profile/domain/repo/edit_profile_repo_contract.dart'
    as _i2;
import 'package:flowery/features/edit_profile/domain/use_cases/get_logged_user_use_case.dart'
    as _i3;
import 'package:flowery/features/edit_profile/domain/use_cases/update_logged_user_use_case.dart'
    as _i8;
import 'package:flowery/features/edit_profile/domain/use_cases/upload_user_photo_use_case.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEditProfileRepoContract_0 extends _i1.SmartFake
    implements _i2.EditProfileRepoContract {
  _FakeEditProfileRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLoggedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLoggedUserUseCase extends _i1.Mock
    implements _i3.GetLoggedUserUseCase {
  MockGetLoggedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeEditProfileRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.EditProfileRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.UserEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.UserEntity>>);
}

/// A class which mocks [UpdateLoggedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateLoggedUserUseCase extends _i1.Mock
    implements _i8.UpdateLoggedUserUseCase {
  MockUpdateLoggedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeEditProfileRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.EditProfileRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.UserEntity>> call(_i9.EditUserModel? editUser) =>
      (super.noSuchMethod(
            Invocation.method(#call, [editUser]),
            returnValue: _i4.Future<_i5.Result<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.UserEntity>>(
                this,
                Invocation.method(#call, [editUser]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.UserEntity>>);
}

/// A class which mocks [UploadUserPhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadUserPhotoUseCase extends _i1.Mock
    implements _i10.UploadUserPhotoUseCase {
  MockUploadUserPhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeEditProfileRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.EditProfileRepoContract);

  @override
  _i4.Future<_i5.Result<_i6.UserEntity>> call(_i11.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#call, [photo]),
            returnValue: _i4.Future<_i5.Result<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.UserEntity>>(
                this,
                Invocation.method(#call, [photo]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.UserEntity>>);
}
